services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api
  api:
    build: ./api
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
  db:
    build: ./db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: