server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    # Redirige todo lo que empiece con /api/ hacia nuestro contenedor de la API
    location /api/ {
        proxy_pass http://api:3000/api/;
    }
}